### ISSUE TITLE
Section 3.1 - MP_CAPABLE exchange

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/draft-ietf-mptcp-rfc6824bis#11]
(From Phil)
> However in Section 3.1 I think it would be good to include a more extensive figure about this - showing the different ways & timings for when the ack is known to have been delivered - ie figure showing somehow that A or B may be one that first sends data - and therefore when A knows that the ACK has indeed been successfully delivered to B.
> The actual text (in the para starting " If B has data to send first, then the reliable delivery of the ACK...") is pretty good - however, there are a lot of "this packet", "this is" etc - likely that   someone could misinterpret what a "this" refers to. A figure would help clarify and/or breaking the text up .

> << Note that new subflows MUST NOT be established                                                                                                                                                         >    (using the process documented in Section 3.2) until a Data Sequence                                                                                                                                    >    Signal (DSS) option has been successfully received across the path                                                                                                                                     >    (as documented in Section 3.3).>>
> In the case where A sends data first, then the MP-CAPABLE is sent instead of the DSS. Does the text quoted mean that new subflows are not allowed (until an actual DSS is sent) or are they allowed       because DSS has kind of been inferred?

> [phil2] the figure in S2.1 (ie in the Operation Overview section) should be modified. As it is compulsory to send the MP_CAPABLE ACK       message on the first data packet. Sending MP_CAPABLE ACK without data is done if host A doesn't have data to send, but you still have to     send ACK later with the first data. Whereas the natural way to interpret the current fig in S2.1 is that the Ack is sent once.

**Comment by ajf101** [comment]
Some rewording done in S3.1 ... new diagrams in S2.1 ... the MUST not thing (second point) does not need changing.

**Comment by cpaasch** [comment]
Changes in the PR look good to me. Closing.
