### ISSUE TITLE
Section 3.7 - Fallback

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/draft-ietf-mptcp-rfc6824bis#12]
Something that needs fixing which Christoph and I just noticed during a chat at the IETF:

S3.7 on Fallback has
<<Note that this rule essentially prohibits the sending of data on the
   third packet of an MP_CAPABLE or MP_JOIN handshake, since both that
   option and a DSS cannot fit in TCP option space.>>
this needs a mod now data is allowed on the third packet.

**Comment by ajf101** [comment]
Can be resolved just by removing that paragraph. Rest of section still holds.

**Comment by cpaasch** [comment]
Changes in the PR look good to me. Closing.
