### ISSUE TITLE
Section 5 - Security

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/draft-ietf-mptcp-rfc6824bis#7]
(From Phil Eardley)
> Section 5 - Security
> This section needs updating to reflect the changes in the bis.:
>
> Discuss the revised MP_CAPABLE
> I'm not sure if the new fast close option (option R) has any security impact?
> Discuss the MP_PRIO change (no off path address indication)
> Discuss downgrade attacks (to v0) during connection initiation

**Comment by ajf101** [comment]
Added discussion of version, MP_PRIO. No additional text needed for MP_CAPABLE or FASTCLOSE that I can see.

**Comment by cpaasch** [comment]
Changes in the PR look good to me. Closing.
